name: ednet_code_generation
version: 1.0.0
description: Generate a new EDNetCore project.

homepage: https://github.com/ednet-dev/cms/tree/main/packages/ednet_code_generation
documentation: https://github.com/ednet-dev/cms

environment:
  sdk: '>=3.7.0 <4.0.0'

dependencies:
  ednet_core: ^1.0.0
  path: ^1.9.1
  test: ^1.25.5
  yaml: ^3.1.2
