name: ednet_openapi
description: OpenAPI implementation for EDNet Core domain models
version: 1.0.0
repository: https://github.com/ednet-dev/ednet_core

environment:
  sdk: ">=2.17.0 <3.0.0"

dependencies:
  ednet_core:
    path: ../core
  meta: ^1.8.0
  shelf: ^1.4.0
  shelf_router: ^1.1.3
  shelf_static: ^1.1.1
  http: ^0.13.5
  path: ^1.8.3
  yaml: ^3.1.1
  json_annotation: ^4.7.0

dev_dependencies:
  lints: ^2.0.1
  test: ^1.22.0
  build_runner: ^2.3.2
  json_serializable: ^6.5.4
