name: EDNetDev
packages:
  - "apps/*"
  - "packages/core"
  - "packages/ednet_code_generation"
  - "packages/ednet_cms"

# Recommended option for projects with Dart 2.17.0 or greater.
#
# This enables a new mechanism for linking local packages, which integrates
# better with other tooling (e.g. dart tool, flutter tool, IDE plugins) than the
# mechanism currently being used by default. Please read the documentation for
# usePubspecOverrides before enabling this feature.
#
# See https://melos.invertase.dev/getting-started#setup
command:
  bootstrap:
    usePubspecOverrides: true

scripts:
  analyze:
    run: melos exec -- "flutter analyze"
    description: Run `flutter analyze` in all packages

  analyze:core:
    run: melos exec --scope="core" -- "dart analyze"
    description: Run Dart analyze for the core package in this project.

  format:
    run: melos exec -- "flutter format . --set-exit-if-changed"
    description: Run `flutter format .` in all packages

  format:core:
    run: melos exec --scope="core" -- "dart format . --set-exit-if-changed"
    description: Run Dart format for the core package in this project.

  test:
    run: melos exec --dir-exists="test" --fail-fast -- "flutter test --no-pub --coverage"
    description: Run all tests in this project.

  test:core:
    run: melos exec --scope="core" -- "dart test --coverage='coverage'"
    description: Run Dart tests for the core package in this project.

  test:dart:
    run: melos exec --dir-exists="test" --no-private --fail-fast -- dart test --coverage="coverage"
    description: Run Dart tests for a specific package in this project.

  publish:dry:
    run: melos publish --scope="ednet_cms" --dry-run
    description: Dry run of publishing ednet_cms to pub.dev.

  publish:
    run: melos publish --scope="ednet_cms" --no-dry-run
    description: Publish ednet_cms to pub.dev.

  publish:dry:core:
    run: melos publish --scope="core" --dry-run
    description: Dry run of publishing core to pub.dev.

  publish:core:
    run: melos publish --scope="core" --no-dry-run
    description: Publish core to pub.dev.