name: EDNetDev
packages:
  - "apps/*"
  - "packages/core"
  - "packages/ednet_code_generation"
  - "packages/ednet_cms"

# Recommended option for projects with Dart 2.17.0 or greater.
#
# This enables a new mechanism for linking local packages, which integrates
# better with other tooling (e.g. dart tool, flutter tool, IDE plugins) than the
# mechanism currently being used by default. Please read the documentation for
# usePubspecOverrides before enabling this feature. 
#
# See https://melos.invertase.dev/getting-started#setup
command:
  bootstrap:
    usePubspecOverrides: true

scripts:
  analyze:
    run: melos exec -- "flutter analyze"
    description: Run `flutter analyze` in all packages

  format:
    run: melos exec -- "flutter format . --set-exit-if-changed"
    description: Run `flutter format .` in all packages

  test:flutter:select:
    run: melos exec --dir-exists="test" --fail-fast -- flutter test --no-pub --coverage
    description: Run Flutter tests for a specific package in this project.
    select-package:
      flutter: true
      dir-exists: test

  test:flutter:
    run: melos run test:flutter:select --no-select
    description: Run all Flutter tests in this project.
    select-package:
      flutter: true
      dir-exists: test

  test:dart:
    run: melos exec --dir-exists="test" --no-private --fail-fast -- dart test --coverage="coverage"
    description: Run Dart tests for a specific package in this project.


  test:
    run: melos run test:dart && melos run test:flutter --no-select

  publish_cms_to_pub_dry:
    run: melos exec --scope="ednet_cms" -- "dart pub publish --dry-run"
    description: Publish ednet_cms to pub.dev test

  publish_cms_to_pub:
    run: melos exec --scope="ednet_cms" -- "dart pub publish --force"
    description: Publish ednet_cms to pub.dev