name: ednet_one_archive
description: EDNet One - A one-stop solution for domain-driven design
version: 0.0.1+1
publish_to: "none"

environment:
  sdk: ">=3.0.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  ednet_core:
    path: ../../packages/core
  ednet_core_flutter:
    path: ../../packages/ednet_core_flutter
  fl_chart: ^0.66.2
  cupertino_icons: ^1.0.8
  flutter_bloc: ^8.1.1
  flutter_slidable: ^2.0.0
  google_fonts: ^3.0.1
  http: ^0.13.5
  intl: ^0.20.2
  json_annotation: ^4.8.0
  provider: ^6.0.5
  shared_preferences: ^2.0.15
  uuid: ^3.0.7
  path: ^1.8.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0
  build_runner: ^2.3.3
  json_serializable: ^6.6.0

flutter:
  uses-material-design: true
  assets:
    - assets/
