name: ednet_one
description: "Integration app"
publish_to: "none" # Remove this line if you wish to publish to pub.dev
version: 1.0.0+1

environment:
  sdk: '>=3.5.0-180.3.beta <4.0.0'
dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  bloc: ^8.1.4
  flutter_bloc: ^8.1.5
  app_links: ^6.1.1
  ednet_core:
    path: ../../packages/core
  ednet_cms:
    path: ../../packages/cms
  graphview: ^1.2.0
  flame: ^1.18.0
  flutter_svg:
  flame_svg: ^1.10.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0
  build_runner: ^2.4.10
  build_config: ^1.1.1
flutter:
  uses-material-design: true
  assets:
    - assets/sprites/

