name: ednet_event_storming
description: Event storming toolkit for EDNet - supporting Domain-Driven Design's collaborative modeling approach
version: 0.1.0
homepage: https://github.com/ednet-dev/cms/tree/main/packages/ednet_event_storming

environment:
  sdk: ">=3.7.0 <4.0.0"

dependencies:
  ednet_core:
    path: ../core
  test: ^1.25.8

dev_dependencies:
  build_web_compilers: ^4.0.11
  build_runner: ^2.4.13
