targets:
  $default:
    builders:
      ednet_cms|hello_world:
        generate_for:
          - domain/**/*.yaml

builders:
  hello_world:
    import: "package:ednet_cms/src/builders/hello_world_builder.dart"
    builder_factories: [ "helloWorldBuilder" ]
    build_extensions: { ".yaml": [ ".dart" ] }
    auto_apply: root_package
    build_to: source
    runs_before: [ source_gen|combining_builder ]
    applies_builders: [ source_gen|combining_builder ]
