targets:
  $default:
    builders:
      ednet_cms|cmsBuilder:
        enabled: false

  initialize:
    builders:
      ednet_cms|contentWatcherBuilder:
        enabled: false


builders:
  ednet_cms|jsonContentWatcherBuilder:
    import: "package:ednet_cms/ednet_cms.dart"
    builder_factories: [ "jsonContentWatcherBuilder" ]
    build_to: source
    auto_apply: none
    build_extensions:
      ".json": [ "_ednet_json.g.dart" ]

  ednet_cms|cmsBuilder:
    import: "package:ednet_cms/ednet_cms.dart"
    builder_factories: [ "cmsBuilder" ]
    auto_apply: dependents
    build_to: source
    build_extensions:
      ".ednet.yaml": [ "_cms.g.dart" ]

  ednet_cms|contentWatcherBuilder:
    import: "package:ednet_cms/ednet_cms.dart"
    auto_apply: none
    build_to: source
    builder_factories: [ "contentWatcherBuilder" ]
    build_extensions:
      ".ednet.yaml": [ "_ednet.g.dart" ]
