targets:
  $default:
    builders:
      ednet_cms|content_watcher_builder:
        generate_for:
          - lib/requirements/**/*.yaml

builders:
  contentWatcherBuilder:
    import: "package:ednet_cms/src/builders/content_watcher_builder.dart"
    builder_factories: [ "contentWatcherBuilder" ]
    build_extensions: { ".yaml": [ ".dart" ] }
    auto_apply: dependents
    build_to: source
    runs_before: [ source_gen|combining_builder ]
    applies_builders: [ source_gen|combining_builder ]
