targets:
  $default:
    builders:
      ednet_cms:
        enabled: true

builders:
  ednet_cms:
    import: 'package:ednet_cms/ednet_cms.dart'
    builder_factories: [ "cmsBuilder" ]
    build_extensions:
      '.dart': [ "_cms.g.dart" ]
      '.yaml': [ "_cms.g.yaml" ]
    build_to: source
    auto_apply: dependents
