name: ednet_cms
description: Semantic CMS tools
version: 0.0.3-dev.3
homepage: https://github.com/ednet-dev/cms/tree/main/packages/ednet_cms

environment:
  sdk: '>=2.18.6 <3.0.0'

dependencies:
  ednet_code_generation: ^0.0.3+1
  ednet_core: ^0.0.1+8
  watcher: ^1.0.2
  args: ^2.4.0
  build: ^2.3.1
  glob: ^2.1.1

dev_dependencies:
  test: 1.22.0
  flutter_lints: ^2.0.1
  build_runner: ^2.3.3
  build_web_compilers: ^3.2.7

executables:
  build:
  watch:

