name: ednet_cms
description: Semantic CMS tools
version: 0.0.1+2
homepage: https://github.com/ednet-dev/cms/tree/f9ec655efbd482be239d23127dac24b5453e59b2/packages/ednet_cms

environment:
  sdk: '>=2.18.6 <3.0.0'

dependencies:
  ednet_core: ^0.0.1+2

dev_dependencies:
  test: 1.22.0
  flutter_lints: ^2.0.1

