name: ednet_dev_tools
description: Developer tools for EDNet ecosystem with GitHub workflow integration
version: 0.1.0
repository: https://github.com/ednet-dev/cms

environment:
  sdk: ">=3.0.0 <4.0.0"

dependencies:
  args: ^2.4.0
  ednet_core:
    path: ../core
  meta: ^1.9.0
  path: ^1.8.3
  yaml: ^3.1.2

dev_dependencies:
  lints: ^3.0.0
  test: ^1.24.0

executables:
  ednet: main 