name: ednet_core
description: Set of cool generic tools in modeling domain models based on domain-driven design and event storming
version: 0.0.1+1
homepage: https://github.com/ednet-dev/cms/packages/core
publish_to: "https://pub.dev/packages/ednet_core"

environment:
  sdk: '>=2.18.6 <3.0.0'

dependencies:
  test: 1.22.0

