name: ednet_core
description: Set of cool generic tools in modeling domain models based on domain-driven design and event storming
version: 0.0.1+7
homepage: https://github.com/ednet-dev/cms/tree/main/packages/core

environment:
  sdk: '>=2.18.6 <3.0.0'

dependencies:
  test: ^1.22.0

