name: ednet_core
description: Set of cool generic tools in modeling domain models based on domain-driven design and event storming
version: 1.0.0
homepage: https://github.com/ednet-dev/cms/tree/main/packages/core

environment:
  sdk: ">=3.0.0 <4.0.0"

dependencies:
  expressions: ^0.2.5+2
  test: ^1.25.8
  equatable: ^2.0.5
  shared_preferences: ^2.5.3

dev_dependencies:
  build_web_compilers: ^4.0.11
  build_runner: ^2.4.13
