name: ednet_one_interpreter
description: Shell package for EDNet One application
version: 0.0.1
publish_to: none

environment:
  sdk: ">=3.7.0 <4.0.0"
  flutter: ">=3.29.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_bloc: ^8.1.3
  app_links: ^6.3.2
  shared_preferences: ^2.2.2
  ednet_cms:
    path: ../../packages/cms

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true
