name: ednet_drift
description: Drift/SQLite repository implementation for EDNet Core domain models
version: 1.0.0
repository: https://github.com/ednet-dev/ednet_core

environment:
  sdk: ">=2.17.0 <3.0.0"

dependencies:
  ednet_core:
    path: ../core
  drift: ^2.5.0
  sqlite3_flutter_libs: ^0.5.12
  path: ^1.8.3
  path_provider: ^2.0.12
  meta: ^1.8.0

dev_dependencies:
  lints: ^2.0.1
  test: ^1.22.0
  build_runner: ^2.3.2
  drift_dev: ^2.5.2
