name: ednet_drift_repository
description: "Generic Drift database integration for EDNet Core entities"
version: 0.0.1
homepage: https://github.com/ednet-dev/cms/tree/main/packages/drift/ednet_drift

environment:
  sdk: ">=3.7.0 <4.0.0"
  flutter: ">=3.29.0"

dependencies:
  ednet_core: ^1.0.0
  drift: ^2.26.0

dev_dependencies:
  drift_dev: ^2.26.0
  build_runner: ^2.4.10
  lints: ^4.0.0
  test: ^1.25.8